### PR TITLE
Update window.sumofus references for window.champaign

### PR DESCRIPTION
**Pull request by eyko**
In Champaign, we're only keeping window.sumofus for "legacy templates", so we might as well just update the templates?

### CODE REVIEW

**Comment by rodrei** [comment]
:100: I'm all in for this. We should test it to make sure it's not breaking anything.

Also, what are we doing about the `development` branch on this repo? I noticed you're trying to merge to `master`,  but staging is going to keep loading development. We should either start using `development` in the same way we use it in the champaign repo, or remove the `development` branch and go back to using master. I think I rather use master for now.

**Comment by osahyoun** [comment]
👍 merge?

**Comment by eyko** [comment]
Let's remove the `development` branch then (but it was handy when we were upgrading all those templates and we didn't want to break production)

**Comment by eyko** [comment]
Fixes #27

**Pull request merged**
