### PR TITLE
Added donation form to two-step-share-page

### PR DESCRIPTION
**Pull request by rodrei**
@NealJMD @paulaferris What do we want to do after the user actually makes a donation? Right now it redirects to the page follow-up page which is the same one the member is already in.

### CODE REVIEW

**Comment by paulaferris** [comment]
@rodrei what's simple to implement? I think something that would work well and hopefully be easy would just be to display a thank you message in place of the fundraising form on the same page for now. "Thanks so much for your donation! We really appreciate your support." (and translated strings in DE and FR).

We'll probably iterate at some point but I think that would work for now.

**Comment by rodrei** [comment]
@paulaferris that sounds simple and a fairly good solution. Although optimally I think we should display some sort of content: an option could be a widget with featured campaigns.

**Comment by paulaferris** [comment]
Agree! I just know we're still testing in this area so don't want to over-polish something that will likely change.

**Comment by rodrei** [comment]
This is updated and working! The only thing outstanding is a small UI glitch with the sticky footer, I'll take a look at it tomorrow.

**Comment by rodrei** [comment]
Closing this PR since it's being replaced by https://github.com/SumOfUs/sou-assets/pull/11

( I need it to have the name `two-step-share` to match Champaign's PR )

**Pull request closed without merging**
